pre-commit:
    parallel: true
    commands:
        lint-staged:
            run: npx --no-install lint-staged
            root: .
commit-msg:
    commands:
        commitlint:
            run: npx --no-install commitlint --edit $1
            root: .

pre-push:
    commands:
        lint:
            run: pnpm lint
            root: .
        test:
            run: pnpm test
            root: .
